// transcript-golden-rows.ts — the payload matrix of the transcript hook's
// golden differential (spec 0247 plan, verification duty 2): every event the
// four CLIs are wired to, harness texts, numbers, null, false, objects, a
// transcript tail, long multi-byte content, every token rule and every stub
// mode. Read by transcript-golden-capture.ts, which records the outcomes into
// scripts/tests/fixtures/mempalace-transcript/golden/matrix.json.
//
// `deviation` names the clause of R30 that makes the TypeScript hook differ
// from the shell hook on that row.

import type { GoldenInput } from "./transcript-golden.ts";

type Row = GoldenInput & { readonly description: string; readonly deviation?: string };

const j = (value: unknown): string => JSON.stringify(value);
const said = (content: unknown, type = "ASSISTANT_RESPONSE"): string => j({ type, content });
const C = { session_id: "sess-0123456789", cwd: "/work/proj-a" };
const AGY = { conversationId: "conv-abcdef123456", workspacePaths: ["/ws/agy-proj"] };
const DEFAULT_KEY = "{KEY:{HOME}/.mempalace/palace}";

const TAIL = [
  j({ type: "USER_INPUT", content: "question" }),
  said("first answer"),
  j({ type: "RESPONSE", tool_calls: [{ name: "Read" }, { name: "Bash" }] }),
  said("line one\nline two"),
  said(42),
  j({ type: "PLANNER_RESPONSE", content: "plan" }),
  said("last words"),
].join("\n");

export const GOLDEN_ROWS: readonly Row[] = [
  // --- Claude Code: PreToolUse, UserPromptSubmit, PostToolUse, Stop, SessionEnd ---
  {
    id: "claude-prompt",
    description: "UserPromptSubmit",
    args: [],
    mode: "ok",
    stdin: j({ hook_event_name: "UserPromptSubmit", prompt: "hello world", ...C }),
  },
  {
    id: "claude-prompt-env",
    description: "CLAUDE_SESSION_ID and CLAUDE_PROJECT_DIR win over the payload",
    args: [],
    mode: "ok",
    env: { CLAUDE_SESSION_ID: "claude-env-session", CLAUDE_PROJECT_DIR: "/work/from-env" },
    stdin: j({ hook_event_name: "UserPromptSubmit", prompt: "p", ...C }),
  },
  {
    id: "claude-harness-literal",
    description: "a harness literal",
    args: [],
    mode: "ok",
    stdin: j({
      hook_event_name: "UserPromptSubmit",
      prompt: "<system-reminder>be nice</system-reminder>",
      ...C,
    }),
  },
  {
    id: "claude-harness-line",
    description: "the harness ERE on a later line",
    args: [],
    mode: "ok",
    stdin: j({
      hook_event_name: "UserPromptSubmit",
      prompt: "hi\n  <foo-notification id=1>body",
      ...C,
    }),
  },
  {
    id: "claude-harness-message",
    description: "the [Message] timestamp= literal",
    args: [],
    mode: "ok",
    stdin: j({ hook_event_name: "UserPromptSubmit", prompt: "[Message] timestamp=1 x", ...C }),
  },
  {
    id: "claude-not-harness",
    description: "a tag that is not at the start of a line",
    args: [],
    mode: "ok",
    stdin: j({ hook_event_name: "UserPromptSubmit", prompt: "x <foo-reminder>", ...C }),
  },
  {
    id: "claude-prompt-null-literal",
    description: "the literal text null",
    args: [],
    mode: "ok",
    stdin: j({ hook_event_name: "UserPromptSubmit", prompt: "null", ...C }),
  },
  {
    id: "claude-prompt-null",
    description: "a JSON null prompt",
    args: [],
    mode: "ok",
    stdin: j({ hook_event_name: "UserPromptSubmit", prompt: null, ...C }),
  },
  {
    id: "claude-prompt-false",
    description: "false is skipped by //, user_input is used",
    args: [],
    mode: "ok",
    stdin: j({ prompt: false, user_input: "fallback", ...C }),
  },
  {
    id: "claude-prompt-number",
    description: "a number is rendered",
    args: [],
    mode: "ok",
    stdin: j({ hook_event_name: "UserPromptSubmit", prompt: 42, ...C }),
  },
  {
    id: "claude-prompt-object",
    description: "an object prompt",
    args: [],
    mode: "ok",
    deviation: "R30/non-scalar-values",
    stdin: j({ hook_event_name: "UserPromptSubmit", prompt: { a: 1 }, ...C }),
  },
  {
    id: "claude-prompt-true",
    description: "a true prompt",
    args: [],
    mode: "ok",
    deviation: "R30/non-scalar-values",
    stdin: j({ hook_event_name: "UserPromptSubmit", prompt: true, ...C }),
  },
  {
    id: "claude-pretool-command",
    description: "PreToolUse with a command",
    args: [],
    mode: "ok",
    stdin: j({
      hook_event_name: "PreToolUse",
      tool_name: "Bash",
      tool_input: { command: "ls -la" },
      ...C,
    }),
  },
  {
    id: "claude-pretool-file",
    description: "PreToolUse with a file path",
    args: [],
    mode: "ok",
    stdin: j({
      hook_event_name: "PreToolUse",
      tool_name: "Read",
      tool_input: { file_path: "/a/b.ts" },
      ...C,
    }),
  },
  {
    id: "claude-pretool-pattern",
    description: "PreToolUse with a pattern",
    args: [],
    mode: "ok",
    stdin: j({
      hook_event_name: "PreToolUse",
      tool_name: "Grep",
      tool_input: { pattern: "foo.*" },
      ...C,
    }),
  },
  {
    id: "claude-pretool-noargs",
    description: "PreToolUse with no argument",
    args: [],
    mode: "ok",
    stdin: j({ hook_event_name: "PreToolUse", tool_name: "LS", tool_input: {}, ...C }),
  },
  {
    id: "claude-pretool-empty-command",
    description: "an empty command is selected",
    args: [],
    mode: "ok",
    stdin: j({
      hook_event_name: "PreToolUse",
      tool_name: "Bash",
      tool_input: { command: "", file_path: "/x" },
      ...C,
    }),
  },
  {
    id: "claude-posttool",
    description: "PostToolUse is skipped",
    args: [],
    mode: "ok",
    stdin: j({
      hook_event_name: "PostToolUse",
      tool_name: "Bash",
      tool_input: { command: "ls" },
      ...C,
    }),
  },
  {
    id: "claude-stop-transcript",
    description: "Stop summarises the transcript tail",
    args: [],
    mode: "ok",
    transcript: `${TAIL}\n`,
    stdin: j({ hook_event_name: "Stop", transcript_path: "{TMP}/transcript.jsonl", ...C }),
  },
  {
    id: "claude-stop-camel",
    description: "transcriptPath",
    args: [],
    mode: "ok",
    transcript: `${said("camel")}\n`,
    stdin: j({ hook_event_name: "Stop", transcriptPath: "{TMP}/transcript.jsonl", ...C }),
  },
  {
    id: "claude-stop-missing",
    description: "a transcript path that does not exist",
    args: [],
    mode: "ok",
    stdin: j({ hook_event_name: "Stop", transcript_path: "{TMP}/absent.jsonl", ...C }),
  },
  {
    id: "claude-stop-long-tail",
    description: "more than 20 lines and more than 5 responses",
    args: [],
    mode: "ok",
    transcript: `${Array.from({ length: 30 }, (_, i) => said(`r${i}`)).join("\n")}\n`,
    stdin: j({ hook_event_name: "Stop", transcript_path: "{TMP}/transcript.jsonl", ...C }),
  },
  {
    id: "claude-stop-bad-line",
    description: "a transcript line that does not parse",
    args: [],
    mode: "ok",
    deviation: "R30/exit-status",
    transcript: `${said("before")}\n{bad\n${said("after")}\n`,
    stdin: j({ hook_event_name: "Stop", transcript_path: "{TMP}/transcript.jsonl", ...C }),
  },
  {
    id: "claude-stop-object",
    description: "an object content in the tail",
    args: [],
    mode: "ok",
    deviation: "R30/stop-summary-objects",
    transcript: `${said({ k: "v" })}\n${said("text")}\n`,
    stdin: j({ hook_event_name: "Stop", transcript_path: "{TMP}/transcript.jsonl", ...C }),
  },
  {
    id: "claude-stop-two-byte",
    description: "500-byte cut on a 2-byte boundary",
    args: [],
    mode: "ok",
    transcript: `${said("é".repeat(300))}\n`,
    stdin: j({ hook_event_name: "Stop", transcript_path: "{TMP}/transcript.jsonl", ...C }),
  },
  {
    id: "claude-stop-three-byte",
    description: "500-byte cut inside a 3-byte character",
    args: [],
    mode: "ok",
    deviation: "R30/character-boundaries",
    transcript: `${said("€".repeat(300))}\n`,
    stdin: j({ hook_event_name: "Stop", transcript_path: "{TMP}/transcript.jsonl", ...C }),
  },
  {
    id: "claude-session-end",
    description: "SessionEnd without a source",
    args: [],
    mode: "ok",
    stdin: j({ hook_event_name: "SessionEnd", reason: "logout", ...C }),
  },
  {
    id: "claude-session-start-override",
    description: "SessionStart replaces a prompt entry",
    args: [],
    mode: "ok",
    stdin: j({ hook_event_name: "SessionStart", source: "startup", prompt: "ignored", ...C }),
  },

  // --- Gemini CLI: BeforeTool, BeforeAgent, AfterTool, AfterModel, SessionEnd ---
  {
    id: "gemini-before-agent",
    description: "BeforeAgent prompt",
    args: [],
    mode: "ok",
    env: { GEMINI_SESSION_ID: "gem-session-42", GEMINI_PROJECT_DIR: "/g/gem-proj" },
    stdin: j({ hook_event_name: "BeforeAgent", prompt: "from gemini" }),
  },
  {
    id: "gemini-user-input",
    description: "userInput (camel case)",
    args: [],
    mode: "ok",
    env: { GEMINI_SESSION_ID: "gem-session-42" },
    stdin: j({ userInput: "camel input", cwd: "/g/p" }),
  },
  {
    id: "gemini-before-tool",
    description: "BeforeTool",
    args: [],
    mode: "ok",
    env: { GEMINI_SESSION_ID: "gem" },
    stdin: j({
      hook_event_name: "BeforeTool",
      tool_name: "run_shell_command",
      tool_input: { command: "npm test" },
      cwd: "/g/p",
    }),
  },
  {
    id: "gemini-after-tool",
    description: "AfterTool",
    args: [],
    mode: "ok",
    stdin: j({
      hook_event_name: "AfterTool",
      tool_name: "read_file",
      tool_input: { file_path: "/g/x" },
      session_id: "s",
      cwd: "/g/p",
    }),
  },
  {
    id: "gemini-after-model",
    description: "AfterModel",
    args: [],
    mode: "ok",
    stdin: j({ hook_event_name: "AfterModel", model_response: "the answer", cwd: "/g/p" }),
  },
  {
    id: "gemini-after-model-camel",
    description: "modelResponse",
    args: [],
    mode: "ok",
    stdin: j({ modelResponse: "camel answer", cwd: "/g/p" }),
  },
  {
    id: "gemini-after-model-long",
    description: "2000 characters, then 4000 bytes on a boundary",
    args: [],
    mode: "ok",
    stdin: j({ hook_event_name: "AfterModel", model_response: "é".repeat(2500), cwd: "/g/p" }),
  },
  {
    id: "gemini-after-model-euro",
    description: "4000 bytes inside a 3-byte character",
    args: [],
    mode: "ok",
    deviation: "R30/character-boundaries",
    stdin: j({ hook_event_name: "AfterModel", model_response: "€".repeat(2500), cwd: "/g/p" }),
  },
  {
    id: "gemini-session-end",
    description: "SessionEnd with a source",
    args: [],
    mode: "ok",
    stdin: j({ hook_event_name: "SessionEnd", source: "exit", cwd: "/g/p" }),
  },

  // --- Copilot CLI: sessionStart, userPromptSubmitted, postToolUse, agentStop, sessionEnd ---
  {
    id: "copilot-session-start",
    description: "no event name, nothing to record",
    args: [],
    mode: "ok",
    stdin: j({ sessionId: "cop-1", cwd: "/c/proj", source: "new", timestamp: 1 }),
  },
  {
    id: "copilot-prompt",
    description: "userPromptSubmitted",
    args: [],
    mode: "ok",
    stdin: j({ sessionId: "cop-session-1", cwd: "/c/proj", prompt: "from copilot", timestamp: 1 }),
  },
  {
    id: "copilot-post-tool",
    description: "postToolUse carries toolName, which is not read",
    args: [],
    mode: "ok",
    stdin: j({ sessionId: "cop-1", cwd: "/c/proj", toolName: "bash", toolArgs: "{}" }),
  },
  {
    id: "copilot-agent-stop",
    description: "agentStop",
    args: [],
    mode: "ok",
    stdin: j({ sessionId: "cop-1", cwd: "/c/proj" }),
  },
  {
    id: "copilot-session-number",
    description: "a numeric session id",
    args: [],
    mode: "ok",
    stdin: j({ sessionId: 123456789012, cwd: "/c/proj", prompt: "n" }),
  },

  // --- Antigravity CLI (legacy form: the event as the argument) ---
  {
    id: "agy-stop",
    description: "Stop",
    args: ["Stop"],
    mode: "ok",
    stdin: j({ ...AGY, terminationReason: "completed" }),
  },
  {
    id: "agy-stop-no-reason",
    description: "Stop without a reason",
    args: ["Stop"],
    mode: "ok",
    stdin: j(AGY),
  },
  {
    id: "agy-pre-invocation",
    description: "PreInvocation",
    args: ["PreInvocation"],
    mode: "ok",
    stdin: j({ ...AGY, invocationNum: 3, modelName: "gemini-x" }),
  },
  {
    id: "agy-pre-invocation-empty",
    description: "PreInvocation without fields",
    args: ["PreInvocation"],
    mode: "ok",
    stdin: "{}",
  },
  {
    id: "agy-prompt-override",
    description: "a prompt replaces the Antigravity entry",
    args: ["Stop"],
    mode: "ok",
    stdin: j({ ...AGY, prompt: "agy prompt" }),
  },
  {
    id: "agy-other-event",
    description: "an event with no entry",
    args: ["PostInvocation"],
    mode: "ok",
    stdin: j(AGY),
  },
  {
    id: "agy-disabled",
    description: "disabled: the acknowledgement only",
    args: ["Stop"],
    mode: "ok",
    env: { MEMPALACE_TRANSCRIPT_ENABLED: null },
    stdin: j(AGY),
  },
  {
    id: "agy-malformed",
    description: "a payload that does not parse",
    args: ["Stop"],
    mode: "ok",
    deviation: "R30/exit-status",
    stdin: "{bad",
  },
  {
    id: "agy-git-root",
    description: "no workspacePaths: the Git top level",
    args: ["Stop"],
    mode: "ok",
    cwd: "repo",
    stdin: j({ conversationId: "c-1" }),
  },
  {
    id: "agy-session-end-event",
    description: "a SessionEnd hook_event_name replaces the entry",
    args: ["Stop"],
    mode: "ok",
    stdin: j({ ...AGY, hook_event_name: "SessionEnd" }),
  },
  {
    id: "agy-extra-argument",
    description: "Stop extra",
    args: ["Stop", "extra"],
    mode: "ok",
    stdin: j(AGY),
  },

  // --- the direct form (CLI identifiers) ---
  {
    id: "direct-claude-code",
    description: "claude-code with ENABLED unset",
    args: ["claude-code"],
    mode: "ok",
    deviation: "R30/cli-identifiers",
    env: { MEMPALACE_TRANSCRIPT_ENABLED: null },
    stdin: j({ hook_event_name: "UserPromptSubmit", prompt: "direct", ...C }),
  },
  {
    id: "direct-antigravity-cli",
    description: "antigravity-cli Stop",
    args: ["antigravity-cli", "Stop"],
    mode: "ok",
    deviation: "R30/cli-identifiers",
    stdin: j({ ...AGY, terminationReason: "done" }),
  },
  {
    id: "direct-wrong-arity",
    description: "claude-code Stop",
    args: ["claude-code", "Stop"],
    mode: "ok",
    deviation: "R30/cli-identifiers",
    stdin: j({ prompt: "x", ...C }),
  },

  // --- standard input, gating, logging, project ---
  { id: "stdin-empty", description: "an empty payload", args: [], mode: "ok", stdin: "" },
  {
    id: "stdin-trailing-garbage",
    description: "JSON followed by garbage",
    args: [],
    mode: "ok",
    deviation: "R30/exit-status",
    stdin: "{} x",
  },
  {
    id: "legacy-disabled",
    description: "the legacy form, disabled",
    args: [],
    mode: "ok",
    env: { MEMPALACE_TRANSCRIPT_ENABLED: null },
    stdin: j({ prompt: "p", ...C }),
  },
  {
    id: "quiet",
    description: "QUIET=1 silences the success line",
    args: [],
    mode: "ok",
    env: { MEMPALACE_TRANSCRIPT_QUIET: "1" },
    stdin: j({ prompt: "quiet", ...C }),
  },
  {
    id: "git-root",
    description: "no project named: the Git top level",
    args: [],
    mode: "ok",
    cwd: "repo",
    stdin: j({ prompt: "p", session_id: "s" }),
  },
  {
    id: "cwd-fallback",
    description: "no project and no repository: the working directory",
    args: [],
    mode: "ok",
    stdin: j({ prompt: "p" }),
  },
  {
    id: "multibyte-session",
    description: "the first 8 characters of a multi-byte session id",
    args: [],
    mode: "ok",
    stdin: j({ prompt: "p", session_id: "éèêëàâäô-tail", cwd: "/w/p" }),
  },

  // --- the token (R14) ---
  {
    id: "token-named",
    description: "MEMPALACE_DAEMON_TOKEN_FILE",
    args: [],
    mode: "ok",
    files: { "named/token": "named-token\n", "mock/token": "mock-token\n" },
    env: {
      MEMPALACE_DAEMON_TOKEN_FILE: "{HOME}/named/token",
      TOKEN_PATH_MOCK: "{HOME}/mock/token",
    },
    stdin: j({ prompt: "p", ...C }),
  },
  {
    id: "token-named-missing",
    description: "a missing named file is final",
    args: [],
    mode: "ok",
    files: { "mock/token": "mock-token\n" },
    env: { MEMPALACE_DAEMON_TOKEN_FILE: "{HOME}/nope/token", TOKEN_PATH_MOCK: "{HOME}/mock/token" },
    stdin: j({ prompt: "p", ...C }),
  },
  {
    id: "token-mock",
    description: "TOKEN_PATH_MOCK",
    args: [],
    mode: "ok",
    files: {
      "mock/token": "mock-token\n",
      [`.mempalace/server/${DEFAULT_KEY}/token`]: "computed\n",
    },
    env: { MEMPALACE_DAEMON_TOKEN_FILE: null, TOKEN_PATH_MOCK: "{HOME}/mock/token" },
    stdin: j({ prompt: "p", ...C }),
  },
  {
    id: "token-mock-missing",
    description: "a missing mock is final",
    args: [],
    mode: "ok",
    files: { ".mempalace/server/0first/token": "w\n" },
    env: { MEMPALACE_DAEMON_TOKEN_FILE: null, TOKEN_PATH_MOCK: "{HOME}/nope" },
    stdin: j({ prompt: "p", ...C }),
  },
  {
    id: "token-computed",
    description: "the palace-keyed path",
    args: [],
    mode: "ok",
    files: {
      [`.mempalace/server/${DEFAULT_KEY}/token`]: "computed\n",
      ".mempalace/server/0first/token": "wild\n",
    },
    env: { MEMPALACE_DAEMON_TOKEN_FILE: null },
    stdin: j({ prompt: "p", ...C }),
  },
  {
    id: "token-wildcard",
    description: "the first server/*/token when the computed one is missing",
    args: [],
    mode: "ok",
    files: {
      ".mempalace/server/1second/token": "second\n",
      ".mempalace/server/0first/token": "first\n",
    },
    env: { MEMPALACE_DAEMON_TOKEN_FILE: null },
    stdin: j({ prompt: "p", ...C }),
  },
  {
    id: "token-palace-path",
    description: "MEMPALACE_PALACE_PATH: one server directory, found by both",
    args: [],
    mode: "ok",
    files: { ".mempalace/server/{KEY:/srv/palace}/token": "custom\n" },
    env: { MEMPALACE_DAEMON_TOKEN_FILE: null, MEMPALACE_PALACE_PATH: "/srv/palace" },
    stdin: j({ prompt: "p", ...C }),
  },
  {
    id: "token-mempalace-path",
    description: "MEMPALACE_PATH keyed the shell's lookup",
    args: [],
    mode: "ok",
    deviation: "R30/token-key",
    files: {
      ".mempalace/server/{KEY:/srv/legacy}/token": "legacy\n",
      [`.mempalace/server/${DEFAULT_KEY}/token`]: "default\n",
    },
    env: { MEMPALACE_DAEMON_TOKEN_FILE: null, MEMPALACE_PATH: "/srv/legacy" },
    stdin: j({ prompt: "p", ...C }),
  },
  {
    id: "token-whitespace",
    description: "whitespace removed",
    args: [],
    mode: "ok",
    files: { "t/token": " to\tk en \r\n\n" },
    stdin: j({ prompt: "p", ...C }),
  },
  {
    id: "token-empty",
    description: "an empty token",
    args: [],
    mode: "ok",
    deviation: "R30/empty-token",
    files: { "t/token": " \n" },
    stdin: j({ prompt: "p", ...C }),
  },
  {
    id: "token-none",
    description: "no token anywhere",
    args: [],
    mode: "ok",
    files: {},
    env: { MEMPALACE_DAEMON_TOKEN_FILE: null },
    stdin: j({ prompt: "p", ...C }),
  },

  // --- the daemon's answers (R15) ---
  {
    id: "daemon-rpc-error",
    description: "a JSON-RPC error",
    args: [],
    mode: "rpc-error",
    stdin: j({ prompt: "p", ...C }),
  },
  {
    id: "daemon-is-error",
    description: "result.isError",
    args: [],
    mode: "is-error",
    stdin: j({ prompt: "p", ...C }),
  },
  {
    id: "daemon-is-error-quiet",
    description: "failures ignore QUIET",
    args: ["Stop"],
    mode: "is-error",
    env: { MEMPALACE_TRANSCRIPT_QUIET: "1" },
    stdin: j(AGY),
  },
  {
    id: "daemon-http-500",
    description: "an HTML 500",
    args: [],
    mode: "http-500-html",
    deviation: "R30/response-classes",
    stdin: j({ prompt: "p", ...C }),
  },
  {
    id: "daemon-hang",
    description: "no answer within 5 s",
    args: ["Stop"],
    mode: "hang",
    deviation: "R30/unreachable-reason",
    stdin: j(AGY),
  },
  {
    id: "daemon-closed",
    description: "a refused connection",
    args: [],
    mode: "closed",
    deviation: "R30/unreachable-reason",
    stdin: j({ prompt: "p", ...C }),
  },

  // --- the trust file (R16) ---
  {
    id: "tls-valid",
    description: "a trust file setup wrote",
    args: [],
    mode: "ok",
    files: {
      "t/token": "tok\n",
      ".crewrig/tls-env.sh": "# setup\nexport NODE_EXTRA_CA_CERTS=/opt/My\\ CA/b.pem\n",
    },
    stdin: j({ prompt: "p", ...C }),
  },
  {
    id: "tls-malformed",
    description: "a trust file with a command in it",
    args: [],
    mode: "ok",
    deviation: "R30/trust-file",
    files: { "t/token": "tok\n", ".crewrig/tls-env.sh": "export A=1\necho sourced-and-run >&2\n" },
    stdin: j({ prompt: "p", ...C }),
  },
];
